server:
  port: 10086
spring:
  application:
    name: eurekaServer
eureka:
  client:
    service-url:
      #false表示不向注册中心注册自己
      register-with-eureka: false
      #表示自己就是注册中心,职责就是维护服务实例
      fetch-registry: false
      defaultZone: http://127.0.0.1:10086/eureka/