server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://82.157.31.31:3306/cloud-order?useSSL=false
    username: root
    password: Root.2022
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderServer
  cloud:
    nacos:
      server-addr: localhost:8848 #注册中心地址
      discovery:
        cluster-name: NJ  #集群名称,区分不同的集群
        namespace: daab179c-3853-4cef-819d-0cd65abf334e #命名空间(环境隔离)
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#负载均衡配置,规则优先会寻找与自己同集群的服务
userServer:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

####Eureka配置start
##Eureka配置,和注册中心地址一致
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/
##单模块负载均衡配置
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #负载均衡规则(负载均衡第二种方式)
##懒加载模式切换为饥饿模式,提升速度
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients: userServer # 指定对userservice这个服务饥饿加载
####Eureka配置end